### ISSUE TITLE
Cart Feature - UI

### ISSUE THREAD

**Issue by afifah-2002** [afifah-2002/GrabNGo#10]
As a developer, I want to implement a cart feature that allows users to add multiple items, modify quantities, and review their selections before proceeding to checkout, so that they can easily manage their orders and make any necessary changes before purchasing.

## Estimation Effort
Large

## Acceptance Criteria
o Users should be able to add multiple items into the cart
o Users should be able to modify the quantity of each item in the cart
o The cart must allow users to remove individual items
o Users should be able to review all selections and modifications before proceeding to
checkout
o The cart design must be responsive so that it can be used across all devices like desktop,
tablet or mobile
o The design should be user friendly and should contain all added items with clear
information, including item names, quantities, and individual prices.
o The cart must display the final price, including item costs for the user to review before
checking out
o The total price should update automatically with any changes to the cart.

**Comment by SanjanaMynedi** [comment]
Development is completed
