### ISSUE TITLE
Transaction Management - Backend

### ISSUE THREAD

**Issue by afifah-2002** [afifah-2002/GrabNGo#7]
As an admin, I want to maintain a database of all users so that I can manage user accounts, keep track of their orders to ensure seamless transaction.

## Estimation of Effort
Medium

## Acceptance Criteria
o I should be able to view detailed user profiles containing their user ids and contact details
and
o I need the ability to search for users using filters such as name or email
o The database should be so that it can handle growing user data over time.
o I should have the ability to add or delete users in case of any reports on the user
o The database must maintain a comprehensive log of purchase history that users can easily
access and review.

**Comment by SanjanaMynedi** [comment]
Transaction Management has been implemented
