### ISSUE TITLE
Login/Sign up - UI

### ISSUE THREAD

**Issue by afifah-2002** [afifah-2002/GrabNGo#8]
As a developer, I want to add login and signup pages so that users can keep track of their orders.

## Estimation of Effort
Medium

## Acceptance Criteria
o The signup page must collect necessary information such as name, email, and password
o Users should receive feedback for incorrect login attempts like invalid username or
password
o Users should be able to reset their password through email authentication in case they
forget their password
o The design should be responsive so it can be used both in my phone and laptop

**Comment by SanjanaMynedi** [comment]
Login/sign up feature is developed
